### ISSUE TITLE
Reformationstag 2017

### ISSUE THREAD

**Issue by mbohlaender** [mayflower/libholiday#13]
Shouldn't the reformationstag added to Germany? Because it is a holiday for all german federal states.

**Comment by froschdesign** [comment]
@mbohlaender 
> Shouldn't the reformationstag added to Germany?

Is already there. Look at the classes:

- [`Brandenburg`](https://github.com/mayflower/libholiday/blob/master/src/Holiday/Brandenburg.php#L24)
- [`MecklenburgWesternPomerania`](https://github.com/mayflower/libholiday/blob/master/src/Holiday/MecklenburgWesternPomerania.php#L25)
- [`Saxony`](https://github.com/mayflower/libholiday/blob/master/src/Holiday/Saxony.php#L25)
- [`SaxonyAnhalt`](https://github.com/mayflower/libholiday/blob/master/src/Holiday/SaxonyAnhalt.php#L26)
- [`Thuringia`](https://github.com/mayflower/libholiday/blob/master/src/Holiday/Thuringia.php#L25)

> …all german federal states.

[Only in this year!](https://de.wikipedia.org/wiki/Reformationstag#Deutschland)

**Comment by calbrecht** [comment]
Actually it is already in 9 of them [q=Reformationstag](https://github.com/mayflower/libholiday/search?utf8=%E2%9C%93&q=Reformationstag&type=)
e.g [BadenWuerttemberg](https://github.com/mayflower/libholiday/blob/62733d8be2236638e8bfd68b5de17fb90f686fca/src/Holiday/BadenWuerttemberg.php#L31)

will be happy to accept a PR with the missing ones for 2017 :-)
