### ISSUE TITLE
set up the new GitHub Hook for Packagist

### ISSUE THREAD

**Issue by xalopp** [mayflower/libholiday#21]
I get this message, when I visit https://packagist.org/packages/mayflower/holiday

> This package is using the legacy GitHub service and will stop being auto-updated in early 2019. Please set up the new (https://packagist.org/about#how-to-update-packages)[GitHub Hook] for Packagist so that it keeps working in the future.

Could a project admin setup the new Github Hook for this project, so packagist stops complaining?

**Comment by mmoll** [comment]
TBH, I'd rather advocate to deprecate and archive this project or are there any real world usages known as of today?

**Comment by Ma27** [comment]
Can we gather some stats (e.g. from packagist) about the usage and popularity? IIRC this was originally developed for PHProjekt, but I'm wondering as well if we should invest time into maintaining this library.

**Comment by xalopp** [comment]
@Ma27 https://packagist.org/packages/mayflower/holiday/stats
And there 3 projects relying on `mayflower/holiday` : https://packagist.org/packages/mayflower/holiday/dependents

TO_BIG_TO_FAIL ❗️ 😄

**Comment by Ma27** [comment]
I agree with @mmoll here, but I'd suggest to notify the maintainer of `mcs/bol-plaza-v2` first as that library seems to be used by some folks.

**Comment by mmoll** [comment]
@Ma27 AFAICT, there's only one project that's depending on it and still alive (https://github.com/meertensm/bol-plaza-v2). Otherwise, the last release was 2016 and the main contributors of the last significant changes 2015 have forked and extended it in an backwarts-incompatible in the meanwhile (https://github.com/kruu-com/libholiday).

**Comment by Ma27** [comment]
Not sure if I'm missing something, but the latest release is just 5 days old: https://github.com/meertensm/bol-plaza-v2/releases/tag/0.2.16

But it's certainly good to know that there's a fork (which seems at least a bit more active than this) that we can recommend :+1:

**Comment by mmoll** [comment]
> the latest release is just 5 days old

Yes, I meant releases of this project itself.

**Comment by mmoll** [comment]
Two weeks without any further replies or actions.

I'll go ahead and archive this repo. :derelict_house:
